# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libcairo2-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libgif-dev \
    build-essential \
    g++

# Copy the current directory contents into the container at /app
COPY . /app

# Install a compatible version of npm
RUN npm install -g npm@latest

# Clear npm cache
RUN npm cache clean --force

# Configure npm to use a different registry
RUN npm config set registry https://registry.npmjs.org/

# Install any needed packages specified in package.json
RUN npm install --legacy-peer-deps

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev"]
