services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    networks:
      - ifss-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ifss-network

networks:
  ifss-network:
    driver: bridge
