# Stage 1: Build the C++ binary
FROM gcc:latest AS builder
WORKDIR /app

# Copy the necessary files for compilation
COPY . /app

# Run the Makefile to compile the code
RUN make

# Stage 2: Build the Python application
FROM python:3.9-slim
WORKDIR /app

# Copy the compiled binary from the builder stage
COPY --from=builder /app/build/taxCalculator /app/build/taxCalculator

# Copy the rest of the application code
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME World

# Run main.py when the container launches
CMD ["python3", "src/app.py"]

